name: size_adapter
description: Supercharge Flutter responsiveness! Scale your app effortlessly for pixel-perfect layouts on all screens. Get responsive with size_adapter!
version: 0.0.2
homepage: https://github.com/3kdeveloper
repository: https://github.com/3kdeveloper/size_adapter

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
