name: size_adapter
description: Supercharge Flutter responsiveness! Scale your app effortlessly for pixel-perfect layouts on all screens. Get responsive with size_adapter!
version: 0.0.1
homepage: https://github.com/3kdeveloper
repository: https://github.com/3kdeveloper/size_adapter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: